### Performance Metrics on MultiClass Classification

In [1]:
from sklearn import metrics

c:\users\ag20459\appdata\local\continuum\anaconda3\envs\tf2_2\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
C="Cat"
D="Dog"
F="Fox"

In [4]:
# True Values
y_true = [C,C,C,C,C,C, F,F,F,F,F,F,F,F,F, D,D,D,D,D,D,D,D,D,D,D]
#pred_value
y_pred = [C,C,C,C,D,F, C,C,C,C,C,D,D,F,F, C,C,C,D,D,D,D,D,D,D,D]

#Print the confusion matrix
print(metrics.confusion_matrix(y_true, y_pred))

#Print the precision and recall,among other metrics
print(metrics.classification_report(y_true, y_pred, digits=3))

[[4 1 1]
 [3 8 0]
 [5 2 2]]
              precision    recall  f1-score   support

         Cat      0.333     0.667     0.444         6
         Dog      0.727     0.727     0.727        11
         Fox      0.667     0.222     0.333         9

    accuracy                          0.538        26
   macro avg      0.576     0.539     0.502        26
weighted avg      0.615     0.538     0.526        26

